theme: jekyll-theme-minimal
title: "Searching Related Mathematical Expressions with Machine Learning"
description: "We provide a dataset of equations represented as PNG-images and Latex code. This dataset is useful for learning to detect similarities in equations."
show_downloads: "true"
logo: "ls8.png"
